mutation REGISTER_USER(

  $email: String!,
  $username: String!,
  $firstName: String!,
  $lastName: String!,
  $password: String!
) {
  registerUser(
    newUser: {
      email: $email,
      username: $username,
      firstName: $firstName,
      lastName: $lastName,
      password: $password
    }
  ){
    token
    user {
      id
      email
      username
    }
  }
}
# Test query params / payload
{
  "email": "test@test.com",
  "username": "test",
  "firstName": "Testy",
  "lastName": "McTest", 
  "password": "password123"

}