mutation REGISTER_USER(

  $email: String!,
  $username: String!,
  $firstName: String!,
  $lastName: String!,
  $password: String!
) {
  registerUser(
    newUser: {
      email: $email,
      username: $username,
      firstName: $firstName,
      lastName: $lastName,
      password: $password
    }
  ){
    token
    user {
      id
      email
      username
    }
  }
}
# Test query params / payload
{
  "email": "test@test.com",
  "username": "test",
  "firstName": "Testy",
  "lastName": "McTest", 
  "password": "password123"

}

# Login User
query LOGIN_USER(
  $email: String!,
  $password: String!
){
  loginUser(
    email: $email,
    password: $password
  ){
    token
    user {
      #removed id cause was throwing error? check database 
      email
      username
    }
  }
  
}
# loginUser payload query variables
# {
#   "username": "test2",
#   "password": super secret password you know
# }
